git:
  depth: 1
language: python
python:
- '3.6'
install:
- pip install -r servicecatalog_puppet/requirements.txt
- pip install .
script:
- pip install pytest==4.4.0
- pip install pytest-cov==2.6.1
- pip install codecov
- pytest --cov=./ servicecatalog_puppet
before_deploy:
- python setup.py sdist
deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: sdist bdist_wheel
    on:
      tags: true
      repo: awslabs/aws-service-catalog-puppet-framework
      all_branches: true
    user:
      secure: hl3b67RDXOrCikjpyZoYyAPBL/Sa2LiYOE8qxKaBhdJv3uzR3PMYKm22zFuhlaOx/FzGmq6rmYLxc+Yqe7Q/hEQOH5C6DjMVIW9LtW1W9RtoXwURJizeOdF2OSb5FkWG1y9TTWDIMTHXiInIUG10WOqHw68iegCl/JXkE6Rgi8lqBMzHEXKtEoQPoMKtX7+lxy6cSeTDZepzU64WwhZ+GldYG2GLoCiITIubYABnuMQZzwarLBwzlu4KwvVON1wkaOdsLJaVikYdHEn2Y61ao/Gm5p7rGNBPy21ra316YwQBuvQorl5uIG8dLJIuG68b41uwGO0iIhcLyos7MAmLhKe8Cigyd0+CNpkaZushRIusbouPX3TGqAdpyc5+oinurggWpTEAUjpc/pb8pP6a16epPGIxj/QFdmqEnHpkZcbmhx180Mknj2yv9TUFyi52+SEuVGRfnQiMpKpnz+d73FjTh7HmQfrBPrsAlciwYo+pabLCKoaQSJlCRiw4gBEPdWNLz6iGItDJCSSCPeuGBz+ZeezlGjUrFvtpASCaeL5WKEyZk8CGI9Eg3HYs6L3JBSfdr1mrY43QDwBoYP8yq+l6L2pS/XkfXjNEd6ipvHOz77bQDPZ6oMeCmRsDn3hg77sCgpL2uKkiGYW+CEDej8ALPngkmbWfkDLIECcIIv0=
    password:
      secure: nOdKMbemEuM6whVO7eq/egIQ0Vl69SurCrSFUrxhTGNeF6jiU81QpWe2BW8gWzlIJjSqVHsRhQ0O7iGzSqCFGWVEyh8BymGqomJRMXWl8gJDdIayJcIfJIQLc3EY17pOIwSLCM4BCGdgmIEp9wXuyql4jhMfL5LWbihq7xbN0HCSUo8KtONZYIEvO1inroPTf4diHIPbVYLrAto335T5zQRv9JoENHyapx4dj2gwnWMYlHsYDCzZSkaU9Xu4xg8KnfmhiTfOVqWqi7V/e62P0q0hfBzx1ei1ryJ48x/k7EhXLEpbQ/JTwfqs90t3suvDgPwmgUELg86LeUB8tJtc1mufBvhEr4lwDrG0m+pnlA9Ne2Z0iiWt6giQyslCZVsllHP8t7+kvY85BKg+Hb/HvN+OLLSjUBDUFPS5eyQre6Ptmh60UQxGZy2QGIcEOl3Hyg8GxSpQhbEpc3BLeDaki/cIG6M4U6CajsQ1h193Gyy3HeJ60FA47EEAwMTD07YN+gt9ZuxvFBj0TCDFizGLXJyU2JF7AjqGk2bIAj46V5Quup+0El/8Uc2N2pvFXEgnKPIPJTB/YR7wLwLf4yzRZ3Url4veapdw0/p5QPBDpCRnHOJzUA/SFQHfFc5eiSvh2mljgZsuYGzaG48Nz8GJoIz0OHGmXASDKlGNwbNHV4g=
after_success:
- codecov --token=${CODECOV_TOKEN}
